_format_version: "1.1"
_workspace: default
services:
- connect_timeout: 60000
  host: mockbin.org
  name: mockbin
  path: /bin/
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: mockbin-route
    path_handling: v0
    paths:
    - /mock
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  tags:
  - mockbin-svc-tag
  write_timeout: 60000